### ISSUE TITLE
Using cassandra with nodejs-driver to store git, github, and social artifacts.

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#1]
We will use cassandra for storing git(not git repository, but git data), github, and social artifacts.
So, we might need to discuss about why we need it for this and how.

https://github.com/datastax/nodejs-driver

**Comment by sangheestyle** [comment]
First step for this, we need to do the following

a. The data including information of each repo from github.searchRepos should be added into DB.
b. `queryResult` should filter data stored in DB (from a)

We will sprint this for Feb 19 Hackathon.

**Comment by mhakeem** [comment]
Need a sample of the JSON data you receive from Github and what data we need to store from that so that I can create the Cassandra schema.

**Comment by sangheestyle** [comment]
Hey @mhakeem ! Use the following file.

https://github.com/sangheestyle/bigdiff-code/tree/master/examples/sample

**Comment by sangheestyle** [comment]
### nodejs cassandra driver

https://github.com/datastax/nodejs-driver

### Check CQL data types to JavaScript types

http://www.datastax.com/documentation/developer/nodejs-driver/1.0/nodejs-driver/reference/nodejs2Cql3Datatypes.html

### Getting Started with Apache Cassandra and Node.js

http://planetcassandra.org/getting-started-with-apache-cassandra-and-node-js/
http://datastax.github.io/nodejs-driver/getting-started

**Comment by sangheestyle** [comment]
Check CQL data types to JavaScript types

http://www.datastax.com/documentation/developer/nodejs-driver/1.0/nodejs-driver/reference/nodejs2Cql3Datatypes.html

**Comment by sangheestyle** [comment]
Getting Started with Apache Cassandra and Node.js

http://planetcassandra.org/getting-started-with-apache-cassandra-and-node-js/

**Comment by sangheestyle** [comment]
I have problem on inserting. Check the code.

https://github.com/sangheestyle/bigdiff-code/commit/649855dcd920c173e287e097042ff6c536260351

And check SO

http://stackoverflow.com/q/28624130/568901

**Comment by sangheestyle** [comment]
Thank you guys. We can do it now.
