### ISSUE TITLE
Error from filter and clone on server (get issues on rate limit)

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#26]
From server

{ [Error: API rate limit exceeded for sangheestyle.] message: 'API rate limit exceeded for sangheestyle.', statusCode: 403, headers: { server: 'GitHub.com', date: 'Wed, 25 Feb 2015 07:09:58 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '124', connection: 'close', status: '403 Forbidden', 'x-ratelimit-limit': '5000', 'x-ratelimit-remaining': '0', 'x-ratelimit-reset': '1424850215', 'x-github-media-type': 'github.v3; format=json', 'x-xss-protection': '1; mode=block', 'x-frame-options': 'deny', 'content-security-policy': 'default-src \'none\'', 'access-control-allow-credentials': 'true', 'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'access-control-allow-origin': '*', 'x-github-request-id': '689A4A5D:11B4:4AD3456:54ED7545', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-content-type-options': 'nosniff' } }

**Comment by sangheestyle** [comment]
I think the request is too fast. So, I think we need to make frequency per mit lower than right now.

**Comment by Brennan-M** [comment]
How Can I reproduce this error?
Did this occur when you gathered the issues for all the filtered repositories over the course of 2 years? In other words, we were only allowed to gather 5000 issues and then it crashed?

Does github allow for this rate limit to be removed?

Did this occur because of searchRepos or getRepoIssues?

**Comment by sangheestyle** [comment]
I guess this was related to rate-limit on search API. I can't reproduce it now. So, I will close this and then I will reopen if we find same error.

Thanks.
