### ISSUE TITLE
Using mongodb instead of Cassandra

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#30]
I think mongodb might be better to this project in terms of rich query features. Here is my plan. 

a. I make a feature branch: mongodb
b. replace cassandra part to by mongodb

**Comment by sangheestyle** [comment]
I am now replacing repo search part. After, I think it's stable, we can change other parts such as issues.

**Comment by Brennan-M** [comment]
Changed the Issues Part as well now. No more cassandra.
