### ISSUE TITLE
github.js function github.getRepoIssues hangs sometimes

### ISSUE THREAD

**Issue by Brennan-M** [sangheestyle/bigdiff-code#9]
When you run github.js, getRepoIssues works approximately 50% of the time, the other times it will hang for some unknown reason. It is crucial to repair this. Is it a problem that I implemented a recursive method in order to gather all issues with pagination?

**Comment by sangheestyle** [comment]
Nice.

**Comment by sangheestyle** [comment]
I got you.

![screenshot from 2015-02-21 22 36 05](https://cloud.githubusercontent.com/assets/319490/6317595/14993bca-ba1a-11e4-9d13-066fea709888.png)

**Comment by Brennan-M** [comment]
Yeah thats my problem! If you keep running it... Sometimes it works, other
times it does that

**Comment by sangheestyle** [comment]
Got it!

**Comment by sangheestyle** [comment]
Yes, also there has some mismatch of number of items.

![screenshot from 2015-02-21 22 38 41](https://cloud.githubusercontent.com/assets/319490/6317599/6a23059e-ba1a-11e4-84b8-8b47fab89204.png)

**Comment by Brennan-M** [comment]
Yes I realized that as well. I am not sure what that could be. I am
thinking there are some issues with some of the JSON objects for the issues
that couldn't actually be retrieved, so maybe it is a null entry and thus
cassandra skips adding it into the DB.

**Comment by sangheestyle** [comment]
Hey, go to sleep and wake up early! I will fix it over night!

**Comment by Brennan-M** [comment]
I might be wrong (and If I am, simply re-close this issue), but the current implementation will not work I don't think. I tested it and it does not work due to the reasons which I commented on the commit.

**Comment by sangheestyle** [comment]
Actually, the pending is not fixed. However, items are inserted correctly. (165 rows)

**Comment by Brennan-M** [comment]
I tested this, it only inserted 156 issues. Same as before.

**Comment by Brennan-M** [comment]
Also, just out of curiosity, why is this implementation better than the recursive implementation I did? It seems like additional overhead?

**Comment by sangheestyle** [comment]
![screenshot from 2015-02-22 03 13 08](https://cloud.githubusercontent.com/assets/319490/6318182/c824161c-ba40-11e4-89ec-bb50c4a69827.png)

I have tested it. 165 rows or 164 rows in my pc. I don't know which might be better. But, I just thought about minimize parameters.

**Comment by sangheestyle** [comment]
I have rollbacked my code and your last commit is on master branch.

**Comment by Brennan-M** [comment]
Either way we implement it is fine with me. You know better than i do. Your
way may be better, I don't know, I was just curious. Tomorrow I will see if
I can reduce parameters, and stop the hang with my method. Maybe on Monday
we can discuss the tradeoffs between our two methods and decide on the best
impmentation.

**Comment by sangheestyle** [comment]
@Brennan-M Hey, how's going! It's really heavy snow. Let's go to snowfight.

Btw, I hope I found a solution. Check this out

https://github.com/sangheestyle/bigdiff-code/commit/86b729a929a30c4f4ba995b58baa8665d824c5b3

**Comment by Brennan-M** [comment]
Nice! Good catch! Do we want to add that part to the master branch?

**Comment by sangheestyle** [comment]
I have done with cherry-pick.

**Comment by sangheestyle** [comment]
CALLBACK hates us... Need to grap some coffee.

Btw, I don't understand why cassandra DB makes all the client pending or hang when they fail to execute something. This behavior is little bit strange to me.

**Comment by sangheestyle** [comment]
It makes sense. We queried with status: open. So, many of those are new and not assigned to developers.

![screenshot from 2015-02-22 13 24 16](https://cloud.githubusercontent.com/assets/319490/6320248/1d7a301a-ba96-11e4-9947-afb2ea956180.png)
